language: python
python:
  - 3.6
install:
  - pip install -U pip pipenv setuptools wheel
  - cd app; pipenv install --system --dev; cd ..
script:
  - cd app; pipenv run test; cd ..
notifications:
  slack:
    secure: jt3KIUMaBNbFD6N+rwPUkXj3svtkBxp2ac1EC4FQAposdhR6wGpzI7tFC2PBNnZLGfqTsl3QzXG4VvV9ZGtUjcqLTJmVp1hVna1w5MiWiBGM/Qu2FRMDeeuxhIZgOwOGohGcOdCdMIjOeTjrVe7yx9S2LGvIOWVXqDkDa104oHvqBhRy3a0y3HPhwWHkjtgsp0D8b0Zo9OPQG10/QxU32SUPRv0o93qbCMb+p205FFdIeTylxvfjiHjfj5/cWutLex3Vbvs0nuoYBfPOb9unO1ZCtdKe6Rt/zZHGYicWdBCvk35gx/USko2gm9O7EZitblickAhyn2RJtjCwsFC3oT50PWb+oaa0dWOfq2hnypT4MsjyNt4/4exntBEk/7xIjYnZY8oqFKLBxilRpQaZXL0977VU3n3/jFyQB+KrWVNqAYEAv2XBRuyCBwmblk2yXvjlWyGwBn7GpNt5gzICLOsfw5uQf3eSHwK/U7UqsOfqmG70k9TiYAeajBICZnmoVA1Yz+9Yu23ORq9f6TdARtcI0NSLpj+4glga64LOa3H0SnSBD/m4MHWS2iyd5sarZlD53tMyLt/x9lo2EdHi4fxYpziQTB8xK1dFm++mGlGtA2cnBUjLyHhqNubgVOIG+jRuLABgaUMPBSlA7lFhdj4zSDsN4mhnYUuieYMCn04=
