version: "3"
services:
  app:
    build: app
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOCKER_HOST: http://docker:2375
      DEBUG: "1"
    volumes:
      - ./app:/app

  docker:
    image: docker:18.09-dind
    privileged: true
    volumes:
      - ./sandbox:/sandbox
