version: "3"
services:
  app:
    build: app
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOCKER_HOST: docker:2375
      MYPY_PLAY_DEBUG: "1"
    volumes:
      - ./app:/app

  docker:
    image: docker:18.03-dind
    privileged: true
    volumes:
      - ./sandbox:/sandbox
