version: "3"
services:
  app:
    build: app
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOCKER_HOST: http://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      DEBUG: "1"
      ENABLE_PROMETHEUS: "1"
      # Example to use Cloud Functions
      # SANDBOX: mypy_playground.sandbox.cloud_functions.CloudFunctionsSandbox
      # We can issue one using CLI: gcloud auth print-identity-token
      # CLOUD_FUNCTIONS_IDENTITY_TOKEN: TOKEN
      # CLOUD_FUNCTIONS_BASE_URL: https://REGION-PROJECT.cloudfunctions.net
      # CLOUD_FUNCTIONS_NAMES: latest:mypy-latest
    volumes:
      - docker_certs:/certs
      - ./app:/app

  frontend:
    build: app/frontend
    volumes:
      - ./app/frontend:/app
      - ./app/static:/static

  docker:
    image: docker:20.10-dind
    privileged: true
    environment:
      DOCKER_TLS_CERT_DIR: /certs
    volumes:
      - docker_certs:/certs
      - ./sandbox/docker:/sandbox

volumes:
  docker_certs:
