debug = "1"
enable-prometheus = "1"

default-python-version = "3.10"
python-versions = ["3.9", "3.10", "3.11"]

# Example to use Cloud Functions
# sandbox = "mypy_playground.sandbox.cloud_functions.CloudFunctionsSandbox"
cloud-functions-base-url = "https://REGION-PROJECT.cloudfunctions.net"
# We can issue one using CLI: gcloud auth print-identity-token
cloud-functions-identity-token = "TOKEN"

[tool-versions]
mypy = [["latest", "latest"]]
basedmypy = [["1.5.0", "basedmypy-1.5.0"]]
pylint = [["2.15.0", "pylint-2.15.0"]]

[cloud-functions-names]
latest = "mypy-latest"

[docker-images]
mypy-latest = "ymyzk/mypy-playground-sandbox:mypy-latest"
"basedmypy-1.5.0" = "ymyzk/mypy-playground-sandbox:basedmypy-1.5.0"
"pylint-2.15.0" = "ymyzk/mypy-playground-sandbox:pylint-2.15.0"
