debug = "1"
enable-prometheus = "1"

default-python-version = "3.11"
python-versions = ["3.9", "3.10", "3.11"]
mypy-versions = [
    ["mypy latest", "latest"],
    ["basedmypy 2.1.0", "basedmypy-2.1.0"],
]

# Example to use Cloud Functions
# sandbox = "mypy_playground.sandbox.cloud_functions.CloudFunctionsSandbox"
cloud-functions-base-url = "https://REGION-PROJECT.cloudfunctions.net"
# We can issue one using CLI: gcloud auth print-identity-token
cloud-functions-identity-token = "TOKEN"

[cloud-functions-names]
latest = "mypy-latest"
"basedmypy 2.1.0" = "basedmypy-2.1.0"

[docker-images]
latest = "ymyzk/mypy-playground-sandbox:latest"
"basedmypy 2.1.0" = "ymyzk/mypy-playground-sandbox:basedmypy-2.1.0"
