[tool.mypy]
python_version = '3.11'
strict = true

[[tool.mypy.overrides]]
module = [
    'google.*',
]
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "I", "W", "UP"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "I001"]
