name: CI
on: [push]
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./app/frontend
    - name: Build, lint, and test frontend
      run: |
        npm run build
        npm run lint
        npm run test
      working-directory: ./app/frontend

  build:
    needs:
      - build_frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
