name: CI
on: [push]
env:
  APP_IMAGE_NAME: ymyzk/mypy-playground
  SANDBOX_IMAGE_NAME: ymyzk/mypy-playground-sandbox
  DOCKER_BUILDKIT: 1
jobs:
  test_app:
    name: Test app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade packaging tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements.dev.txt
      working-directory: ./app
    - name: Run flake8
      run: flake8
      working-directory: ./app
    - name: Run mypy
      run: mypy .
      working-directory: ./app

  test_frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./app/frontend
    - name: Build, lint, and test frontend
      run: |
        npm run build
        npm run lint
        npm run test
      working-directory: ./app/frontend

  build_docker_images:
    name: Build and push Docker images
    needs:
      - test_app
      - test_frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker version
      - name: Build app image for development
        run: docker build --pull -t app:dev ./app
      - name: Build app image for production
        run: docker build --pull -t app:latest -f ./app/Dockerfile-prod ./app
      - name: Build latest sandbox image
        if: github.ref != 'refs/heads/master'
        run: docker build -t sandbox:latest ./sandbox/latest
      - name: Build sandbox images
        if: github.ref == 'refs/heads/master'
        run: ./sandbox/build.sh $SANDBOX_IMAGE_NAME
      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - name: Push app image
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag app:latest $APP_IMAGE_NAME:latest
          docker push $APP_IMAGE_NAME:latest
      - name: Push sandbox images
        if: github.ref == 'refs/heads/master'
        run: ./sandbox/push.sh $SANDBOX_IMAGE_NAME
